name: Cypress Tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # - name: Build app
      #   run: npm run build  # Commented out if not needed

      - name: Run Cypress tests
        run: npx cypress run
