name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # Ensure no build step is here
      # - name: Build app
      #   run: npm run build

      - name: Run Cypress tests
        run: npx cypress run
