name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.7.6
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust as necessary for your project

      - name: Install dependencies
        run: npm install  # Ensure to install all dependencies before running Cypress
      
      - name: Start the application
        run: npm start &  # Start your application in the background

    
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.7.6
        with:
          browser: chrome  # You can specify the browser you want to use